# Generated by Django 4.0.4 on 2022-05-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aadhaar_address_correction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=100)),
                ('document', models.CharField(max_length=100)),
                ('upload_document', models.CharField(max_length=255)),
                ('your_message', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DOB_correction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=100)),
                ('document', models.CharField(max_length=100)),
                ('upload_document', models.CharField(max_length=255)),
                ('your_message', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Name_correction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=100)),
                ('document', models.CharField(max_length=100)),
                ('upload_document', models.CharField(max_length=255)),
                ('your_message', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='New_ration_card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=100)),
                ('document', models.CharField(max_length=100)),
                ('upload_document', models.CharField(max_length=255)),
                ('your_message', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pan_card_apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=100)),
                ('document', models.CharField(max_length=100)),
                ('upload_document', models.CharField(max_length=255)),
                ('your_message', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pan_re_print',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=100)),
                ('document', models.CharField(max_length=100)),
                ('upload_document', models.CharField(max_length=255)),
                ('your_message', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Passport_major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=100)),
                ('document', models.CharField(max_length=100)),
                ('upload_document', models.CharField(max_length=255)),
                ('your_message', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Passport_minor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=100)),
                ('document', models.CharField(max_length=100)),
                ('upload_document', models.CharField(max_length=255)),
                ('your_message', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='re_pan_card_correction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=100)),
                ('document', models.CharField(max_length=100)),
                ('upload_document', models.CharField(max_length=255)),
                ('your_message', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Voter_id_new_apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=100)),
                ('document', models.CharField(max_length=100)),
                ('upload_document', models.CharField(max_length=255)),
                ('your_message', models.CharField(max_length=255)),
            ],
        ),
    ]
