# Generated by Django 4.0.4 on 2022-05-04 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aadhaar_address_correction',
            name='upload_document',
            field=models.FileField(null=True, upload_to='files/', verbose_name=''),
        ),
    ]
